# =============================================================================
# PRODUCTION - Optimized for production deployment
# =============================================================================
# Usage:
#     docker compose -f .devcontainer/compose/prod.yml up -d
# =============================================================================

services:
  web:
    build:
      context: ../../
      dockerfile: .devcontainer/build/nginx.Dockerfile
      target: production
    image: leodg/courses-landing-pages:main
    container_name: courses-nginx
    restart: unless-stopped
    environment:
      - APP_URL=https://courses.ivana.academy
      - APP_ENV=production
      - ENVIRONMENT=production
    volumes:
      - ./logs_nginx:/var/log/nginx
    ports:
      - "8088:80"
    networks:
      - global-network

    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  global-network:
    external: true